---
abstract: 'Perl Interface to L<ViewText.org|http:/www.viewtext.org>'
author:
  - 'Nikola Knezevic, C<< <laladelausanne at gmail.com> >>'
  - 'Nikola Knezevic <laladelausanne@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-ViewText
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  JSON: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
